### ISSUE TITLE
Everything works great except one visual bug

### ISSUE THREAD

**Issue by danrneal** [gotylergo/google-voice-ext-redesign#1]
![Screen Shot 2019-04-10 at 9 13 43 AM](https://user-images.githubusercontent.com/34819234/55895545-392a0d00-5b71-11e9-896d-318bc7d20774.png)

**Comment by gotylergo** [comment]
I'm not seeing this bug. Could this be another extension conflicting? Can you try in an incognito window?

What OS and version of Chrome?

**Comment by danrneal** [comment]
I verified that it still does this in incognito mode.  This is on MacOS on Chrome Version 73.0.3683.86.  I found that there was an error listed on my extension page.

![Screen Shot 2019-04-10 at 1 49 28 PM](https://user-images.githubusercontent.com/34819234/55912571-d13aed00-5b97-11e9-9cca-bd9aa87c67ec.png)

EDIT: I think the error may be unrelated but not 100% sure

**Comment by gotylergo** [comment]
Thanks for the additional info. I'll see if I can reproduce.

**Comment by gotylergo** [comment]
Fixed in commit 46e4511
